### ISSUE TITLE
Metadata preview image linking to localhost

### ISSUE THREAD

**Issue by pedroacamargo** [NECC/SCI#117]
I was working on an application and while trying to get the metadata from Sci website, I received a localhost link
![image](https://github.com/user-attachments/assets/bbcb3fd3-d49e-4311-84be-83ffbe465a83)
![image](https://github.com/user-attachments/assets/7ab3354e-bed3-4216-b20c-9639238166d0)

**Comment by edgararaj** [comment]
After this change its required too add the environment variable PRODUCTION_URL to production. Like this:
`PRODUCTION_URL=https://65fc6a4a39feaf000793b196--sciuminho.netlify.app`
